name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Features'
    labels:
      - feature
      - enhancement
  - title: 'Bug Fixes'
    labels:
      - bug
      - fix
  - title: 'Documentation'
    labels:
      - docs
  - title: 'Maintenance'
    labels:
      - chore
      - refactor
      - build
      - ci
change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
no-changes-template: 'No user-facing changes'
